### ISSUE TITLE
[Feature Request] Add a scrollbar to the vertical menu

### ISSUE THREAD

**Issue by Astriel** [Laravel-Backpack/theme-coreuiv4#52]
# Feature Request

### What I am trying to achieve

Would it be possible to make the vertical menu with all items and dropdowns with a scrollbar ? On my project, the content is actually quite big, and I'm struggling to scroll inside it.

### How I see it implemented

An option in the layout design for big vertical menu to be easily scrollable.

**Comment by tabacitu** [comment]
Hi @Astriel ,

I'll answer because I'm the anti-visible-scrollbar guy here 🙋‍♂️😅

We don't plan on doing that, no. But you should be able to do it yourself, it's just a bit of CSS after all. You should be able to place `overflow-y: scroll` on the element you're interested in, and have it in your admin panel only. You can easily add CSS to all admin panel pages in Backpack: https://backpackforlaravel.com/docs/6.x/base-how-to#add-custom-css-to-all-admin-panel-pages

Hope it helps.
Cheers!
